#ifndef DOCKERFILE_XVFB_WRAPPER
#define DOCKERFILE_XVFB_WRAPPER

USER root
RUN DEBIAN_FRONTEND="noninteractive" apt-get install --no-install-recommends --assume-yes xvfb
// RUN DEBIAN_FRONTEND="noninteractive" apt-get install --no-install-recommends --assume-yes x11-xserver-utils # xrandr
COPY xvfb-wrapper /usr/bin/xvfb-wrapper
USER developer

#endif
// vim: ft=dockerfile
