
ARG WINE_VER=3.0.3

FROM test/wine64:${WINE_VER}
ARG WINEPREFIX="/home/developer/.wine"
LABEL maintainer="j.sebastien.trottier@gmail.com"

ARG FRIM_VER

USER root
RUN apt-get update && \\
    DEBIAN_FRONTEND="noninteractive" apt-get install --no-install-recommends --assume-yes \\
        unzip \\
    && \\
    rm -Rf /var/lib/apt /var/cache/apt /var/log/apt

/* Either use QT_X11_NO_MITSHM=1 or docker run --ipc=host.
 * QT_X11_NO_MITSHM=1 doesn't seem to work.
 */
//ENV QT_X11_NO_MITSHM=1

/* Newer versions of wine require specific capabilities for networking */
// RUN setcap cap_net_raw+epi `/usr/local/bin/wine64`
// RUN setcap cap_net_raw+epi `/usr/local/bin/wine`
// RUN setcap cap_net_raw+epi /usr/local/lib/wine/wineserver TODO!

// #include <Dockerfile.add-developer-user.in>
USER developer

RUN mkdir -v -p \\
        "/home/developer/Downloads" \\
        "/home/developer/Desktop" \\
        "/home/developer/My Documents" && \\
    rmdir -v "${WINEPREFIX}/drive_c/users/developer/Downloads" && \\
    ln -v -s "/home/developer/Downloads" "${WINEPREFIX}/drive_c/users/developer/Downloads" && \\
    rmdir -v "${WINEPREFIX}/drive_c/users/developer/Desktop" && \\
    ln -v -s "/home/developer/Desktop" "${WINEPREFIX}/drive_c/users/developer/Desktop" && \\
    ln -v -s "/home/developer" "/home/developer/Desktop/Home" && \\
    rm -v "${WINEPREFIX}/drive_c/users/developer/My Documents" && \\
    ln -v -s "/home/developer/My Documents" "${WINEPREFIX}/drive_c/users/developer/My Documents"

ARG FILE_FRIM_ZIP
COPY --chown=developer:developer ${FILE_FRIM_ZIP} .
RUN unzip ${FILE_FRIM_ZIP} && \\
    mv FRIM_x64_version_${FRIM_VER} FRIM

COPY --chown=developer:developer volumes-init entrypoint /home/developer/

ENTRYPOINT ["/home/developer/entrypoint"]
