#!/bin/bash

set -euo pipefail

release_url="https://www.makemkv.com/forum/viewtopic.php?f=3&t=224"

PREFIX=${PREFIX:-/usr/local}
PREFIX_SUDO=$([[ -w "$PREFIX" ]] || echo sudo)
maybe_sudo=$([[ "$USER" = "root" ]] || echo sudo)

if (( $# )) ; then
    version=$1 ; shift
else
    version=
fi

prog="$0"
cd "$(dirname "$prog")"

if type -P wget > /dev/null ; then
    function dl() {
	wget -c "$1"
    }
    function dl_pipe() {
	wget -O - -c "$1"
    }
elif type -P curl > /dev/null ; then
    function dl() {
	curl -L -o "$(basename "$1")" "$1"
    }
    function dl_pipe() {
	curl -L "$1"
    }
else
    echo "Neither wget or curl is installed. Please install one." >&2
    exit 1
fi

if [[ -z "$version" ]] ; then
    echo -n "MakeMKV version [latest]: "
    read version
fi

if [[ -z "$version" ]] || [[ "$version" = "latest" ]] ; then
    echo "Looking for latest MakeMKV version..."
    version=$( (dl_pipe "$release_url" 2> /dev/null || true) | sed -n -e 's/.*MakeMKV \([0-9.]\+\) for Linux is available.*/\1/p ; T ; q')
    if [[ -z "$version" ]] ; then
        echo "Latest version not found in $release_url" >&2
        exit 1
    fi
    echo "Using MakeMKV version $version"
fi

if [[ -e /etc/debian_version ]] ; then
    (set -x && $maybe_sudo apt-get install qtbase5-dev libssl-dev zlib1g-dev libexpat1-dev libavcodec-dev libavutil-dev)
elif [[ -e /etc/arch-release ]] ; then
    (set -x && $maybe_sudo pacman --needed -S base-devel qt5-base openssl zlib expat ffmpeg)
fi

dl http://www.makemkv.com/download/makemkv-oss-${version}.tar.gz
dl http://www.makemkv.com/download/makemkv-bin-${version}.tar.gz

tar xzf makemkv-oss-${version}.tar.gz
tar xzf makemkv-bin-${version}.tar.gz

#exit 1

(
set -x
cd makemkv-oss-${version}
patch -p0 < ../makemkv-oss.non-root-ldconfig.patch || true
./configure --prefix "$PREFIX"
make -O -j
$PREFIX_SUDO make install
)

#(cd makemkv-bin-${version} && mkdir -p tmp && touch tmp/eula_accepted)

(
set -x
cd makemkv-bin-${version}
make
$PREFIX_SUDO make install PREFIX="$PREFIX"
)

#exit 1

rm -Rf makemkv-oss-${version} makemkv-bin-${version}
rm -Rf makemkv-oss-${version}.tar.gz makemkv-bin-${version}.tar.gz
