/*
 * See https://wiki.winehq.org/Building_Wine
 */

#include <Dockerfile.macros.in>

ARG WINE_VER
FROM qualip/wine32-build:${WINE_VER} as build

FROM ubuntu:20.04
LABEL maintainer="j.sebastien.trottier@gmail.com"

ARG WINE_TAG
ARG WINE_VER

/* i386 */
RUN dpkg --add-architecture i386
RUN apt-get update && \\
    DEBIAN_FRONTEND="noninteractive" apt-get install --no-install-recommends --assume-yes \\
        -o APT::Immediate-Configure=0 \\
        binfmt-support \\
        libc6-i386 libc6:i386 \\
        libfreetype6:i386 \\
        libx11-6:i386 \\
        libgstreamer-plugins-base1.0:i386 \\
        libxext6:i386 \\
        libxml2:i386 \\
        libmpg123-0:i386 \\
        libgnutls30:i386 \\
    && \\
    RUN_CLEAN_APT && RUN_CLEAN_TMP && RUN_CLEAN_LOG

RUN mkdir -m 1777 /tmp/.X11-unix/
COPY --from=build /usr/local/ /usr/local/

#include <Dockerfile.add-developer-user.in>

ARG WINEPREFIX="/home/developer/.wine32"
ENV WINEPREFIX=${WINEPREFIX}
ENV WINEARCH=win32
RUN wineboot && wineboot --shutdown && wineserver -w && RUN_CLEAN_TMP

// vim: ft=dockerfile
