/*
 * See https://wiki.winehq.org/Building_Wine
 */

ARG WINE_VER
FROM test/wine64-build:${WINE_VER} as build

FROM ubuntu:20.04
LABEL maintainer="j.sebastien.trottier@gmail.com"

ARG WINE_TAG
ARG WINE_VER

/* amd64 */
RUN apt-get update && \\
    DEBIAN_FRONTEND="noninteractive" apt-get install --no-install-recommends --assume-yes \\
        -o APT::Immediate-Configure=0 \\
        binfmt-support \\
        libc6 \\
        libfreetype6 \\
        libx11-6 \\
        libgstreamer-plugins-base1.0 \\
        libxext6 \\
        libxml2 \\
        libmpg123-0 \\
        libgnutls30 \\
    && \\
    rm -Rf /var/lib/apt /var/cache/apt /var/log/apt

RUN mkdir -m 1777 /tmp/.X11-unix
COPY --from=build /usr/local/ /usr/local/

#include <Dockerfile.add-developer-user.in>

ARG WINEPREFIX="/home/developer/.wine64"
ENV WINEPREFIX=${WINEPREFIX}
ENV WINEARCH=win64
RUN wineboot && wineboot --shutdown && wineserver -w

// vim: ft=dockerfile
