
ARG WINE_VER=3.0.3
ARG PACKAGE_VER=

FROM qualip/qaac-build:${PACKAGE_VER} as build

FROM qualip/wine64:${WINE_VER}
ARG WINEPREFIX="/home/developer/.wine"
LABEL maintainer="jst@qualipsoft.com"

COPY --from=build /home/developer/qaac/ /home/developer/qaac/

COPY --chown=developer:developer volumes-init entrypoint /home/developer/

ENTRYPOINT ["/home/developer/entrypoint"]

// vim: ft=dockerfile
