
__all__ = [
        'IsoLang',
        'isolang',
        ]

iso_lang_map = dict()

class IsoLang(object):

    iso639_2 = None
    synonim_iso639_2 = None
    iso639_3 = None
    iso639_5 = None
    iso639_1 = None
    names = None
    native_names = None
    other_names = None
    scope = None
    type = None

    def __str__(self):
        return self.iso639_2

    def __repr__(self):
        return '{}({!r})'.format(
            self.__class__.__name__,
            self.iso639_2)

    def __init__(self, iso639_2, iso639_3, iso639_5, iso639_1, names, scope, type, native_names, other_names, *, synonim_iso639_2=None):
        self.iso639_2 = iso639_2 or None
        self.synonim_iso639_2 = synonim_iso639_2 or None
        self.iso639_3 = iso639_3 or None
        self.iso639_5 = iso639_5 or None
        self.iso639_1 = iso639_1 or None
        self.names = tuple(v.strip() for v in (names or '').split(';'))
        self.scope = scope or None
        self.type = type or None
        self.native_names = tuple(v.strip() for v in (native_names or '').split(';'))
        self.other_names = tuple(v.strip() for v in (other_names or '').split(';'))
        super().__init__()

    @property
    def code2(self):
        return self.iso639_1

    @property
    def code3(self):
        return self.iso639_2

    code = code3

    @property
    def name(self):
        names = self.names
        return names[0] if names else self.iso639_3

    @property
    def map_keys(self):
        map_keys = set()
        for v in (self.code2, self.code3, self.synonim_iso639_2):
            if v:
                map_keys.add(v)
        for name in self.names:
            map_keys.add(name.lower())
        return map_keys

def init_iso_lang(iso639_2, iso639_3, iso639_5, iso639_1, names, scope, type, native_names, other_names, synonim_iso639_2=None):
    lang = IsoLang(iso639_2, iso639_3, iso639_5, iso639_1, names, scope, type, native_names, other_names, synonim_iso639_2=synonim_iso639_2)
    for map_key in lang.map_keys:
        iso_lang_map[map_key] = lang
    return lang

init_iso_lang('aar','aar',None,'aa','Afar','Individual','Living','Qafaraf; ’Afar Af; Afaraf; Qafar af',None)
init_iso_lang('abk','abk',None,'ab','Abkhazian','Individual','Living','Аҧсуа бызшәа; Аҧсшәа','Abkhaz')
init_iso_lang('ace','ace',None,None,'Achinese','Individual','Living','بهسا اچيه','Acehnese')
init_iso_lang('ach','ach',None,None,'Acoli','Individual','Living','Lwo',None)
init_iso_lang('ada','ada',None,None,'Adangme','Individual','Living','Dangme','Dangme')
init_iso_lang('ady','ady',None,None,'Adyghe; Adygei','Individual','Living','Адыгабзэ; Кӏахыбзэ','West Circassian')
init_iso_lang('afa',None,'afa',None,'Afro-Asiatic languages','Collective',None,None,None)
init_iso_lang('afh','afh',None,None,'Afrihili','Individual','Constructed','El-Afrihili',None)
init_iso_lang('afr','afr',None,'af','Afrikaans','Individual','Living','Afrikaans',None)
init_iso_lang('ain','ain',None,None,'Ainu','Individual','Living','アイヌ・イタㇰ',None)
init_iso_lang('aka','aka',None,'ak','Akan','Macrolanguage','Living','Akan',None)
init_iso_lang('akk','akk',None,None,'Akkadian','Individual','Ancient','????????',None)
init_iso_lang('ale','ale',None,None,'Aleut','Individual','Living','Унáӈам тунуý; Унаӈан умсуу',None)
init_iso_lang('alg',None,'alg',None,'Algonquian languages','Collective',None,None,None)
init_iso_lang('alt','alt',None,None,'Southern Altai','Individual','Living','Алтай тили',None)
init_iso_lang('amh','amh',None,'am','Amharic','Individual','Living','አማርኛ',None)
init_iso_lang('ang','ang',None,None,'Old English (ca. 450–1100)','Individual','Historical','Ænglisc; Anglisc; Englisc',None)
init_iso_lang('anp','anp',None,None,'Angika','Individual','Living',None,None)
init_iso_lang('apa',None,'apa',None,'Apache languages','Collective',None,None,'Southern Athabaskan languages')
init_iso_lang('ara','ara',None,'ar','Arabic','Macrolanguage','Living','العَرَبِيَّة',None)
init_iso_lang('arc','arc',None,None,'Official Aramaic (700–300 BCE); Imperial Aramaic (700–300 BCE)','Individual','Ancient',None,None)
init_iso_lang('arg','arg',None,'an','Aragonese','Individual','Living','aragonés',None)
init_iso_lang('arn','arn',None,None,'Mapudungun; Mapuche','Individual','Living',None,None)
init_iso_lang('arp','arp',None,None,'Arapaho','Individual','Living','Hinónoʼeitíít',None)
init_iso_lang('art',None,'art',None,'Artificial languages','Collective',None,None,None)
init_iso_lang('arw','arw',None,None,'Arawak','Individual','Living','Lokono','Lokono')
init_iso_lang('asm','asm',None,'as','Assamese','Individual','Living','অসমীয়া',None)
init_iso_lang('ast','ast',None,None,'Asturian; Bable; Leonese; Asturleonese','Individual','Living','Asturianu',None)
init_iso_lang('ath',None,'ath',None,'Athapascan languages','Collective',None,None,'Athabaskan languages')
init_iso_lang('aus',None,'aus',None,'Australian languages','Collective',None,None,None)
init_iso_lang('ava','ava',None,'av','Avaric','Individual','Living','Магӏарул мацӏ; Авар мацӏ','Avar')
init_iso_lang('ave','ave',None,'ae','Avestan','Individual','Ancient',None,None)
init_iso_lang('awa','awa',None,None,'Awadhi','Individual','Living','अवधी',None)
init_iso_lang('aym','aym',None,'ay','Aymara','Macrolanguage','Living','Aymar aru',None)
init_iso_lang('aze','aze',None,'az','Azerbaijani','Macrolanguage','Living','Azərbaycan dili; آذربایجان دیلی; Азәрбајҹан дили',None)
init_iso_lang('bad',None,'bad',None,'Banda languages','Collective',None,None,None)
init_iso_lang('bai',None,'bai',None,'Bamileke languages','Collective',None,'Bamiléké',None)
init_iso_lang('bak','bak',None,'ba','Bashkir','Individual','Living','Башҡорт теле; Başqort tele',None)
init_iso_lang('bal','bal',None,None,'Baluchi','Macrolanguage','Living','بلوچی','Balochi')
init_iso_lang('bam','bam',None,'bm','Bambara','Individual','Living','ߓߊߡߊߣߊߣߞߊߣ',None)
init_iso_lang('ban','ban',None,None,'Balinese','Individual','Living','ᬪᬵᬱᬩᬮᬶ; ᬩᬲᬩᬮᬶ',None)
init_iso_lang('bas','bas',None,None,'Basa','Individual','Living','Mbene; Ɓasaá','Basaa')
init_iso_lang('bat',None,'bat',None,'Baltic languages','Collective',None,None,None)
init_iso_lang('bej','bej',None,None,'Beja; Bedawiyet','Individual','Living','Bidhaawyeet',None)
init_iso_lang('bel','bel',None,'be','Belarusian','Individual','Living','Беларуская мова',None)
init_iso_lang('bem','bem',None,None,'Bemba','Individual','Living','Chibemba',None)
init_iso_lang('ben','ben',None,'bn','Bengali','Individual','Living','বাংলা',None)
init_iso_lang('ber',None,'ber',None,'Berber languages','Collective',None,'Tamaziɣt; Tamazight; ⵜⴰⵎⴰⵣⵉⵖⵜ; ⵝⴰⵎⴰⵣⵉⵗⵝ; ⵜⴰⵎⴰⵣⵉⵗⵜ','Amazigh languages')
init_iso_lang('bho','bho',None,None,'Bhojpuri','Individual','Living','भोजपुरी',None)
init_iso_lang('bih',None,'bih','bh','Bihari languages','Collective',None,None,None)
init_iso_lang('bik','bik',None,None,'Bikol','Macrolanguage','Living',None,None)
init_iso_lang('bin','bin',None,None,'Bini; Edo','Individual','Living','Ẹ̀dó',None)
init_iso_lang('bis','bis',None,'bi','Bislama','Individual','Living',None,None)
init_iso_lang('bla','bla',None,None,'Siksika','Individual','Living','ᓱᖽᐧᖿ','Blackfoot')
init_iso_lang('bnt',None,'bnt',None,'Bantu languages','Collective',None,None,None)
init_iso_lang('bod','bod',None,'bo','Tibetan','Individual','Living','བོད་སྐད་; ལྷ་སའི་སྐད་',None,synonim_iso639_2='tib')
init_iso_lang('bos','bos',None,'bs','Bosnian','Individual','Living','bosanski; босански',None)
init_iso_lang('bra','bra',None,None,'Braj','Individual','Living',None,'Braj Bhāshā')
init_iso_lang('bre','bre',None,'br','Breton','Individual','Living','Brezhoneg',None)
init_iso_lang('btk',None,'btk',None,'Batak languages','Collective',None,None,None)
init_iso_lang('bua','bua',None,None,'Buriat','Macrolanguage','Living','буряад хэлэн','Buryat')
init_iso_lang('bug','bug',None,None,'Buginese','Individual','Living','ᨅᨔ ᨕᨘᨁᨗ',None)
init_iso_lang('bul','bul',None,'bg','Bulgarian','Individual','Living','български език',None)
init_iso_lang('byn','byn',None,None,'Bilin; Blin','Individual','Living','ብሊና, ብሊን','Bilen')
init_iso_lang('cad','cad',None,None,'Caddo','Individual','Living','Hasí:nay',None)
init_iso_lang('cai',None,'cai',None,'Central American Indian languages','Collective',None,None,None)
init_iso_lang('car','car',None,None,'Galibi Carib','Individual','Living','Kari\'nja','Carib')
init_iso_lang('cat','cat',None,'ca','Catalan; Valencian','Individual','Living','català',None)
init_iso_lang('cau',None,'cau',None,'Caucasian languages','Collective',None,None,None)
init_iso_lang('ceb','ceb',None,None,'Cebuano','Individual','Living','Sinugbuanong Binisayâ',None)
init_iso_lang('cel',None,'cel',None,'Celtic languages','Collective',None,None,None)
init_iso_lang('ces','ces',None,'cs','Czech','Individual','Living','čeština; český jazyk',None,synonim_iso639_2='cze')
init_iso_lang('cha','cha',None,'ch','Chamorro','Individual','Living','Finu\' Chamoru',None)
init_iso_lang('chb','chb',None,None,'Chibcha','Individual','Extinct','Muysccubun',None)
init_iso_lang('che','che',None,'ce','Chechen','Individual','Living','Нохчийн мотт; نَاخچیین موٓتت; ნახჩიე მუოთთ',None)
init_iso_lang('chg','chg',None,None,'Chagatai','Individual','Extinct','جغتای',None)
init_iso_lang('chk','chk',None,None,'Chuukese','Individual','Living',None,None)
init_iso_lang('chm','chm',None,None,'Mari','Macrolanguage','Living','марий йылме',None)
init_iso_lang('chn','chn',None,None,'Chinook jargon','Individual','Living','chinuk wawa; wawa; chinook lelang; lelang',None)
init_iso_lang('cho','cho',None,None,'Choctaw','Individual','Living','Chahta\'',None)
init_iso_lang('chp','chp',None,None,'Chipewyan; Dene Suline','Individual','Living','ᑌᓀᓱᒼᕄᓀ (Dënesųłiné)',None)
init_iso_lang('chr','chr',None,None,'Cherokee','Individual','Living','ᏣᎳᎩ ᎦᏬᏂᎯᏍᏗ',None)
init_iso_lang('chu','chu',None,'cu','Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic','Individual','Ancient','Славе́нскїй ѧ҆зы́къ',None)
init_iso_lang('chv','chv',None,'cv','Chuvash','Individual','Living','Чӑвашла',None)
init_iso_lang('chy','chy',None,None,'Cheyenne','Individual','Living','Tsėhésenėstsestȯtse',None)
init_iso_lang('cmc',None,'cmc',None,'Chamic languages','Collective',None,None,None)
init_iso_lang('cnr','cnr',None,None,'Montenegrin','Individual','Living','crnogorski / црногорски',None)
init_iso_lang('cop','cop',None,None,'Coptic','Individual','Extinct','ϯⲙⲉⲑⲣⲉⲙⲛ̀ⲭⲏⲙⲓ; ⲧⲙⲛ̄ⲧⲣⲙ̄ⲛ̄ⲕⲏⲙⲉ',None)
init_iso_lang('cor','cor',None,'kw','Cornish','Individual','Living','Kernowek',None)
init_iso_lang('cos','cos',None,'co','Corsican','Individual','Living','Corsu; Lingua corsa',None)
init_iso_lang('cpe',None,'cpe',None,'English based Creoles and pidgins','Collective',None,None,None)
init_iso_lang('cpf',None,'cpf',None,'French-based Creoles and pidgins','Collective',None,None,None)
init_iso_lang('cpp',None,'cpp',None,'Portuguese-based Creoles and pidgins','Collective',None,None,None)
init_iso_lang('cre','cre',None,'cr','Cree','Macrolanguage','Living',None,None)
init_iso_lang('crh','crh',None,None,'Crimean Tatar; Crimean Turkish','Individual','Living','Къырымтатарджа; Къырымтатар тили; Ҡырымтатарҗа; Ҡырымтатар тили',None)
init_iso_lang('crp',None,'crp',None,'Creoles and pidgins','Collective',None,None,None)
init_iso_lang('csb','csb',None,None,'Kashubian','Individual','Living','Kaszëbsczi jãzëk','Cassubian')
init_iso_lang('cus',None,'cus',None,'Cushitic languages','Collective',None,None,None)
init_iso_lang('cym','cym',None,'cy','Welsh','Individual','Living','Cymraeg; y Gymraeg',None,synonim_iso639_2='wel')
init_iso_lang('dak','dak',None,None,'Dakota','Individual','Living','Dakhótiyapi; Dakȟótiyapi',None)
init_iso_lang('dan','dan',None,'da','Danish','Individual','Living','dansk',None)
init_iso_lang('dar','dar',None,None,'Dargwa','Individual','Living','дарган мез',None)
init_iso_lang('day',None,'day',None,'Land Dayak languages','Collective',None,None,None)
init_iso_lang('del','del',None,None,'Delaware','Macrolanguage','Living',None,None)
init_iso_lang('den','den',None,None,'Slave (Athapascan)','Macrolanguage','Living','Dene K\'e','Slavey')
init_iso_lang('deu','deu',None,'de','German','Individual','Living','Deutsch',None,synonim_iso639_2='ger')
init_iso_lang('dgr','dgr',None,None,'Dogrib','Individual','Living','डोगरी ڈوگرى',None)
init_iso_lang('din','din',None,None,'Dinka','Macrolanguage','Living','Thuɔŋjäŋ',None)
init_iso_lang('div','div',None,'dv','Dhivehi; Dhivehi; Maldivian','Individual','Living','ދިވެހި; ދިވެހިބަސް',None)
init_iso_lang('doi','doi',None,None,'Dogri','Macrolanguage','Living','डोगरी; ڈوگرى',None)
init_iso_lang('dra',None,'dra',None,'Dravidian languages','Collective',None,None,None)
init_iso_lang('dsb','dsb',None,None,'Lower Sorbian','Individual','Living','Dolnoserbski; Dolnoserbšćina',None)
init_iso_lang('dua','dua',None,None,'Duala','Individual','Living',None,None)
init_iso_lang('dum','dum',None,None,'Middle Dutch (ca. 1050–1350)','Individual','Historical',None,None)
init_iso_lang('dyu','dyu',None,None,'Dyula','Individual','Living','Julakan','Jula')
init_iso_lang('dzo','dzo',None,'dz','Dzongkha','Individual','Living','རྫོང་ཁ་',None)
init_iso_lang('efi','efi',None,None,'Efik','Individual','Living',None,None)
init_iso_lang('egy','egy',None,None,'Egyptian (Ancient)','Individual','Ancient',None,None)
init_iso_lang('eka','eka',None,None,'Ekajuk','Individual','Living',None,'Kajuk')
init_iso_lang('ell','ell',None,'el','Modern Greek (1453–)','Individual','Living','Νέα Ελληνικά',None,synonim_iso639_2='gre')
init_iso_lang('elx','elx',None,None,'Elamite','Individual','Ancient',None,None)
init_iso_lang('eng','eng',None,'en','English','Individual','Living','English',None)
init_iso_lang('enm','enm',None,None,'Middle English (1100–1500)','Individual','Historical',None,None)
init_iso_lang('epo','epo',None,'eo','Esperanto','Individual','Constructed','Esperanto',None)
init_iso_lang('est','est',None,'et','Estonian','Macrolanguage','Living','eesti keel',None)
init_iso_lang('eus','eus',None,'eu','Basque','Individual','Living','euskara',None,synonim_iso639_2='baq')
init_iso_lang('ewe','ewe',None,'ee','Ewe','Individual','Living','Èʋegbe',None)
init_iso_lang('ewo','ewo',None,None,'Ewondo','Individual','Living',None,'Kolo')
init_iso_lang('fan','fan',None,None,'Fang','Individual','Living',None,None)
init_iso_lang('fao','fao',None,'fo','Faroese','Individual','Living','føroyskt',None)
init_iso_lang('fas','fas',None,'fa','Persian','Macrolanguage','Living','فارسی','Farsi',synonim_iso639_2='per')
init_iso_lang('fat','fat',None,None,'Fanti','Individual','Living','Mfantse; Fante; Fanti','Fante')
init_iso_lang('fij','fij',None,'fj','Fijian','Individual','Living','Na Vosa Vakaviti',None)
init_iso_lang('fil','fil',None,None,'Filipino; Pilipino','Individual','Living','Wikang Filipino',None)
init_iso_lang('fin','fin',None,'fi','Finnish','Individual','Living','suomen kieli',None)
init_iso_lang('fiu',None,'fiu',None,'Finno-Ugrian languages','Collective',None,None,'Finno-Ugric languages')
init_iso_lang('fon','fon',None,None,'Fon','Individual','Living','Fon gbè',None)
init_iso_lang('fra','fra',None,'fr','French','Individual','Living','français',None,synonim_iso639_2='fre')
init_iso_lang('frm','frm',None,None,'Middle French (ca. 1400–1600)','Individual','Historical','françois; franceis',None)
init_iso_lang('fro','fro',None,None,'Old French (842–ca. 1400)','Individual','Historical','Franceis; François; Romanz',None)
init_iso_lang('frr','frr',None,None,'Northern Frisian','Individual','Living','Frasch; Fresk; Freesk; Friisk','North Frisian')
init_iso_lang('frs','frs',None,None,'Eastern Frisian','Individual','Living','Seeltersk','Saterland Frisian')
init_iso_lang('fry','fry',None,'fy','Western Frisian','Individual','Living','Frysk','West Frisian')
init_iso_lang('ful','ful',None,'ff','Fulah','Macrolanguage','Living','Fulfulde; Pulaar; Pular','Fula')
init_iso_lang('fur','fur',None,None,'Friulian','Individual','Living','Furlan',None)
init_iso_lang('gaa','gaa',None,None,'Ga','Individual','Living','Gã',None)
init_iso_lang('gay','gay',None,None,'Gayo','Individual','Living','Basa Gayo',None)
init_iso_lang('gba','gba',None,None,'Gbaya','Macrolanguage','Living',None,None)
init_iso_lang('gem',None,'gem',None,'Germanic languages','Collective',None,None,None)
init_iso_lang('gez','gez',None,None,'Geez','Individual','Ancient','ግዕዝ','Ge\'ez')
init_iso_lang('gil','gil',None,None,'Gilbertese','Individual','Living','Taetae ni Kiribati',None)
init_iso_lang('gla','gla',None,'gd','Gaelic; Scottish Gaelic','Individual','Living','Gàidhlig',None)
init_iso_lang('gle','gle',None,'ga','Irish','Individual','Living','Gaeilge',None)
init_iso_lang('glg','glg',None,'gl','Galician','Individual','Living','galego',None)
init_iso_lang('glv','glv',None,'gv','Manx','Individual','Living','Gaelg; Gailck',None)
init_iso_lang('gmh','gmh',None,None,'Middle High German (ca. 1050–1500)','Individual','Historical','Diutsch',None)
init_iso_lang('goh','goh',None,None,'Old High German (ca. 750–1050)','Individual','Historical','Diutisk',None)
init_iso_lang('gon','gon',None,None,'Gondi','Macrolanguage','Living',None,None)
init_iso_lang('gor','gor',None,None,'Gorontalo','Individual','Living','Bahasa Hulontalo',None)
init_iso_lang('got','got',None,None,'Gothic','Individual','Ancient',None,None)
init_iso_lang('grb','grb',None,None,'Grebo','Macrolanguage','Living',None,None)
init_iso_lang('grc','grc',None,None,'Ancient Greek (to 1453)','Individual','Historical','Ἑλληνική',None)
init_iso_lang('grn','grn',None,'gn','Guarani','Macrolanguage','Living','Avañe\'ẽ',None)
init_iso_lang('gsw','gsw',None,None,'Swiss German; Alemannic; Alsatian','Individual','Living','Schwiizerdütsch',None)
init_iso_lang('guj','guj',None,'gu','Gujarati','Individual','Living','ગુજરાતી',None)
init_iso_lang('gwi','gwi',None,None,'Gwichʼin','Individual','Living','Dinjii Zhu’ Ginjik',None)
init_iso_lang('hai','hai',None,None,'Haida','Macrolanguage','Living','X̱aat Kíl; X̱aadas Kíl; X̱aayda Kil; Xaad kil',None)
init_iso_lang('hat','hat',None,'ht','Haitian; Haitian Creole','Individual','Living','kreyòl ayisyen',None)
init_iso_lang('hau','hau',None,'ha','Hausa','Individual','Living','Harshen Hausa; هَرْشَن',None)
init_iso_lang('haw','haw',None,None,'Hawaiian','Individual','Living','ʻŌlelo Hawaiʻi',None)
init_iso_lang('heb','heb',None,'he','Hebrew','Individual','Living','עברית',None)
init_iso_lang('her','her',None,'hz','Herero','Individual','Living','Otjiherero',None)
init_iso_lang('hil','hil',None,None,'Hiligaynon','Individual','Living','Ilonggo',None)
init_iso_lang('him',None,'him [1]',None,'Himachali languages; Western Pahari languages','Collective',None,None,None)
init_iso_lang('hin','hin',None,'hi','Hindi','Individual','Living','हिन्दी',None)
init_iso_lang('hit','hit',None,None,'Hittite','Individual','Ancient','??????',None)
init_iso_lang('hmn','hmn',None,None,'Hmong; Mong','Macrolanguage','Living','lus Hmoob; lug Moob; lol Hmongb',None)
init_iso_lang('hmo','hmo',None,'ho','Hiri Motu','Individual','Living',None,None)
init_iso_lang('hrv','hrv',None,'hr','Croatian','Individual','Living','hrvatski',None)
init_iso_lang('hsb','hsb',None,None,'Upper Sorbian','Individual','Living','hornjoserbšćina',None)
init_iso_lang('hun','hun',None,'hu','Hungarian','Individual','Living','magyar nyelv',None)
init_iso_lang('hup','hup',None,None,'Hupa','Individual','Living','Na:tinixwe Mixine:whe\'',None,None)
init_iso_lang('hye','hye',None,'hy','Armenian','Individual','Living','Հայերէն; Հայերեն',None,synonim_iso639_2='arm')
init_iso_lang('iba','iba',None,None,'Iban','Individual','Living','Jaku Iban',None)
init_iso_lang('ibo','ibo',None,'ig','Igbo','Individual','Living','Asụsụ Igbo',None)
init_iso_lang('ido','ido',None,'io','Ido','Individual','Constructed',None,None)
init_iso_lang('iii','iii',None,'ii','Sichuan Yi; Nuosu','Individual','Living','ꆈꌠꉙ',None)
init_iso_lang('ijo',None,'ijo',None,'Ijo languages','Collective',None,'Ịjọ','Ijaw languages')
init_iso_lang('iku','iku',None,'iu','Inuktitut','Macrolanguage','Living','ᐃᓄᒃᑎᑐᑦ',None)
init_iso_lang('ile','ile',None,'ie','Interlingue; Occidental','Individual','Constructed',None,None)
init_iso_lang('ilo','ilo',None,None,'Iloko','Individual','Living','Pagsasao nga Ilokano; Ilokano','Ilocano')
init_iso_lang('ina','ina',None,'ia','Interlingua (International Auxiliary Language Association)','Individual','Constructed',None,None)
init_iso_lang('inc',None,'inc',None,'Indic languages','Collective',None,None,'Indo-Aryan languages')
init_iso_lang('ind','ind',None,'id','Indonesian','Individual','Living','bahasa Indonesia',None)
init_iso_lang('ine',None,'ine',None,'Indo-European languages','Collective',None,None,None)
init_iso_lang('inh','inh',None,None,'Ingush','Individual','Living','ГӀалгӀай мотт',None)
init_iso_lang('ipk','ipk',None,'ik','Inupiaq','Macrolanguage','Living','Iñupiaq',None)
init_iso_lang('ira',None,'ira',None,'Iranian languages','Collective',None,None,None)
init_iso_lang('iro',None,'iro',None,'Iroquoian languages','Collective',None,None,None)
init_iso_lang('isl','isl',None,'is','Icelandic','Individual','Living','íslenska',None,synonim_iso639_2='ice')
init_iso_lang('ita','ita',None,'it','Italian','Individual','Living','italiano; lingua italiana',None)
init_iso_lang('jav','jav',None,'jv','Javanese','Individual','Living','ꦧꦱꦗꦮ',None)
init_iso_lang('jbo','jbo',None,None,'Lojban','Individual','Constructed','la .lojban.',None)
init_iso_lang('jpn','jpn',None,'ja','Japanese','Individual','Living','日本語',None)
init_iso_lang('jpr','jpr',None,None,'Judeo-Persian','Individual','Living','Dzhidi',None)
init_iso_lang('jrb','jrb',None,None,'Judeo-Arabic','Macrolanguage','Living','عربية يهودية / ערבית יהודית',None)
init_iso_lang('kaa','kaa',None,None,'Kara-Kalpak','Individual','Living','Qaraqalpaq tili; Қарақалпақ тили','Karakalpak')
init_iso_lang('kab','kab',None,None,'Kabyle','Individual','Living','Tamaziɣt Taqbaylit; Tazwawt',None)
init_iso_lang('kac','kac',None,None,'Kachin; Jingpho','Individual','Living','Jingpho',None)
init_iso_lang('kal','kal',None,'kl','Kalaallisut; Greenlandic','Individual','Living',None,None)
init_iso_lang('kam','kam',None,None,'Kamba','Individual','Living',None,None)
init_iso_lang('kan','kan',None,'kn','Kannada','Individual','Living','ಕನ್ನಡ',None)
init_iso_lang('kar',None,'kar',None,'Karen languages','Collective',None,None,'Karenic languages')
init_iso_lang('kas','kas',None,'ks','Kashmiri','Individual','Living','कॉशुर / كأشُر',None)
init_iso_lang('kat','kat',None,'ka','Georgian','Individual','Living','ქართული',None,synonim_iso639_2='geo')
init_iso_lang('kau','kau',None,'kr','Kanuri','Macrolanguage','Living',None,None)
init_iso_lang('kaw','kaw',None,None,'Kawi','Individual','Ancient','ꦧꦱꦗꦮ',None)
init_iso_lang('kaz','kaz',None,'kk','Kazakh','Individual','Living','қазақ тілі / qazaq tili',None)
init_iso_lang('kbd','kbd',None,None,'Kabardian','Individual','Living','Адыгэбзэ (Къэбэрдейбзэ)',None)
init_iso_lang('kha','kha',None,None,'Khasi','Individual','Living','কা কতিয়েন খাশি',None)
init_iso_lang('khi',None,'khi',None,'Khoisan languages','Collective',None,None,None)
init_iso_lang('khm','khm',None,'km','Central Khmer','Individual','Living','ភាសាខ្មែរ',None)
init_iso_lang('kho','kho',None,None,'Khotanese; Sakan','Individual','Ancient',None,'Saka')
init_iso_lang('kik','kik',None,'ki','Kikuyu; Gikuyu','Individual','Living','Gĩkũyũ',None)
init_iso_lang('kin','kin',None,'rw','Kinyarwanda','Individual','Living',None,None)
init_iso_lang('kir','kir',None,'ky','Kirghiz; Kyrgyz','Individual','Living','кыргызча; кыргыз тили',None)
init_iso_lang('kmb','kmb',None,None,'Kimbundu','Individual','Living',None,None)
init_iso_lang('kok','kok',None,None,'Konkani','Macrolanguage','Living','कोंकणी',None)
init_iso_lang('kom','kom',None,'kv','Komi','Macrolanguage','Living','Коми кыв',None)
init_iso_lang('kon','kon',None,'kg','Kongo','Macrolanguage','Living',None,None)
init_iso_lang('kor','kor',None,'ko','Korean','Individual','Living','한국어',None)
init_iso_lang('kos','kos',None,None,'Kosraean','Individual','Living',None,None)
init_iso_lang('kpe','kpe',None,None,'Kpelle','Macrolanguage','Living','Kpɛlɛwoo',None)
init_iso_lang('krc','krc',None,None,'Karachay-Balkar','Individual','Living','Къарачай-Малкъар тил; Таулу тил',None)
init_iso_lang('krl','krl',None,None,'Karelian','Individual','Living','karjal; kariela; karjala',None)
init_iso_lang('kro',None,'kro',None,'Kru languages','Collective',None,None,None)
init_iso_lang('kru','kru',None,None,'Kurukh','Individual','Living','कुड़ुख़',None)
init_iso_lang('kua','kua',None,'kj','Kuanyama; Kwanyama','Individual','Living',None,None)
init_iso_lang('kum','kum',None,None,'Kumyk','Individual','Living','къумукъ тил/qumuq til',None)
init_iso_lang('kur','kur',None,'ku','Kurdish','Macrolanguage','Living','Kurdî / کوردی',None)
init_iso_lang('kut','kut',None,None,'Kutenai','Individual','Living',None,None)
init_iso_lang('lad','lad',None,None,'Ladino','Individual','Living','Judeo-español','Judaeo-Spanish')
init_iso_lang('lah','lah',None,None,'Lahnda','Macrolanguage','Living','بھارت کا','Western Punjabi')
init_iso_lang('lam','lam',None,None,'Lamba','Individual','Living',None,None)
init_iso_lang('lao','lao',None,'lo','Lao','Individual','Living','ພາສາລາວ',None)
init_iso_lang('lat','lat',None,'la','Latin','Individual','Ancient','Lingua latīna',None)
init_iso_lang('lav','lav',None,'lv','Latvian','Macrolanguage','Living','Latviešu valoda',None)
init_iso_lang('lez','lez',None,None,'Lezghian','Individual','Living','Лезги чӏал','Lezgian')
init_iso_lang('lim','lim',None,'li','Limburgan; Limburger; Limburgish','Individual','Living','Lèmburgs',None)
init_iso_lang('lin','lin',None,'ln','Lingala','Individual','Living',None,None)
init_iso_lang('lit','lit',None,'lt','Lithuanian','Individual','Living','lietuvių kalba',None)
init_iso_lang('lol','lol',None,None,'Mongo','Individual','Living','Lomongo',None)
init_iso_lang('loz','loz',None,None,'Lozi','Individual','Living',None,None)
init_iso_lang('ltz','ltz',None,'lb','Luxembourgish; Letzeburgesch','Individual','Living','Lëtzebuergesch',None)
init_iso_lang('lua','lua',None,None,'Luba-Lulua','Individual','Living','Tshiluba','Luba-Kasai')
init_iso_lang('lub','lub',None,'lu','Luba-Katanga','Individual','Living','Kiluba',None)
init_iso_lang('lug','lug',None,'lg','Ganda','Individual','Living','Luganda','Luganda')
init_iso_lang('lui','lui',None,None,'Luiseno','Individual','Living','Cham\'teela',None)
init_iso_lang('lun','lun',None,None,'Lunda','Individual','Living','Chilunda',None)
init_iso_lang('luo','luo',None,None,'Luo (Kenya and Tanzania)','Individual','Living','Dholuo',None)
init_iso_lang('lus','lus',None,None,'Lushai','Individual','Living','Mizo ṭawng','Mizo')
init_iso_lang('mac* / mkd','mkd',None,'mk','Macedonian','Individual','Living','македонски јазик',None)
init_iso_lang('mad','mad',None,None,'Madurese','Individual','Living','Madhura',None)
init_iso_lang('mag','mag',None,None,'Magahi','Individual','Living','मगही',None)
init_iso_lang('mah','mah',None,'mh','Marshallese','Individual','Living','Kajin M̧ajeļ',None)
init_iso_lang('mai','mai',None,None,'Maithili','Individual','Living','मैथिली; মৈথিলী',None)
init_iso_lang('mak','mak',None,None,'Makasar','Individual','Living','Basa Mangkasara\' / ᨅᨔ ᨆᨀᨔᨑ','Makassarese')
init_iso_lang('mal','mal',None,'ml','Malayalam','Individual','Living','മലയാളം',None)
init_iso_lang('man','man',None,None,'Mandingo','Macrolanguage','Living','Mandi\'nka kango','Manding')
init_iso_lang('map',None,'map',None,'Austronesian languages','Collective',None,None,None)
init_iso_lang('mar','mar',None,'mr','Marathi','Individual','Living','मराठी',None)
init_iso_lang('mas','mas',None,None,'Masai','Individual','Living','ɔl',None)
init_iso_lang('mdf','mdf',None,None,'Moksha','Individual','Living','мокшень кяль',None)
init_iso_lang('mdr','mdr',None,None,'Mandar','Individual','Living',None,None)
init_iso_lang('men','men',None,None,'Mende','Individual','Living','Mɛnde yia',None)
init_iso_lang('mga','mga',None,None,'Middle Irish (900–1200)','Individual','Historical','Gaoidhealg',None)
init_iso_lang('mic','mic',None,None,'Mi\'kmaq; Micmac','Individual','Living','Míkmawísimk',None)
init_iso_lang('min','min',None,None,'Minangkabau','Individual','Living','Baso Minang',None)
init_iso_lang('mis','mis',None,None,'Uncoded languages','Special',None,None,None)
init_iso_lang('mkd','mkd',None,'mk','Macedonian','Individual','Living','македонски јазик',None,synonim_iso639_2='mac')
init_iso_lang('mkh',None,'mkh',None,'Mon-Khmer languages','Collective',None,None,'Austroasiatic languages')
init_iso_lang('mlg','mlg',None,'mg','Malagasy','Macrolanguage','Living',None,None)
init_iso_lang('mlt','mlt',None,'mt','Maltese','Individual','Living','Malti',None)
init_iso_lang('mnc','mnc',None,None,'Manchu','Individual','Living','ᠮᠠᠨᠵᡠ ᡤᡳᠰᡠᠨ',None)
init_iso_lang('mni','mni',None,None,'Manipuri','Individual','Living',None,'Meitei')
init_iso_lang('mno',None,'mno',None,'Manobo languages','Collective',None,None,None)
init_iso_lang('moh','moh',None,None,'Mohawk','Individual','Living','Kanien’kéha',None)
init_iso_lang('mon','mon',None,'mn','Mongolian','Macrolanguage','Living','монгол хэл; ᠮᠣᠩᠭᠣᠯ ᠬᠡᠯᠡ',None)
init_iso_lang('mos','mos',None,None,'Mossi','Individual','Living','Mooré',None)
init_iso_lang('mri','mri',None,'mi','Maori','Individual','Living','Te Reo Māori',None,synonim_iso639_2='mao')
init_iso_lang('msa','msa',None,'ms','Malay','Macrolanguage','Living','Bahasa Melayu',None,synonim_iso639_2='may')
init_iso_lang('mul','mul',None,None,'Multiple languages','Special',None,None,None)
init_iso_lang('mun',None,'mun',None,'Munda languages','Collective',None,None,None)
init_iso_lang('mus','mus',None,None,'Creek','Individual','Living','Mvskoke','Muscogee')
init_iso_lang('mwl','mwl',None,None,'Mirandese','Individual','Living','mirandés; lhéngua mirandesa',None)
init_iso_lang('mwr','mwr',None,None,'Marwari','Macrolanguage','Living','मारवाड़ी',None)
init_iso_lang('mya','mya',None,'my','Burmese','Individual','Living','မြန်မာစာ; မြန်မာစကား','Myanmar',synonim_iso639_2='bur')
init_iso_lang('myn',None,'myn',None,'Mayan languages','Collective',None,None,None)
init_iso_lang('myv','myv',None,None,'Erzya','Individual','Living','эрзянь кель',None)
init_iso_lang('nah',None,'nah',None,'Nahuatl languages','Collective',None,None,'Nahuan languages')
init_iso_lang('nai',None,'nai',None,'North American Indian languages','Collective',None,None,None)
init_iso_lang('nap','nap',None,None,'Neapolitan','Individual','Living','napulitano',None)
init_iso_lang('nau','nau',None,'na','Nauru','Individual','Living','dorerin Naoero','Nauruan')
init_iso_lang('nav','nav',None,'nv','Navajo; Navaho','Individual','Living','Diné bizaad; Naabeehó bizaad',None)
init_iso_lang('nbl','nbl',None,'nr','South Ndebele','Individual','Living','isiNdebele seSewula','Southern Ndebele')
init_iso_lang('nde','nde',None,'nd','North Ndebele','Individual','Living','siNdebele saseNyakatho','Northern Ndebele')
init_iso_lang('ndo','ndo',None,'ng','Ndonga','Individual','Living','ndonga',None)
init_iso_lang('nds','nds',None,None,'Low German; Low Saxon','Individual','Living','Plattdütsch; Plattdüütsch',None)
init_iso_lang('nep','nep',None,'ne','Nepali','Macrolanguage','Living','नेपाली भाषा',None)
init_iso_lang('new','new',None,None,'Nepal Bhasa; Newari','Individual','Living','नेवाः भाय्','Newar')
init_iso_lang('nia','nia',None,None,'Nias','Individual','Living','Li Niha',None)
init_iso_lang('nic',None,'nic',None,'Niger-Kordofanian languages','Collective',None,None,'Niger-Congo languages')
init_iso_lang('niu','niu',None,None,'Niuean','Individual','Living','ko e vagahau Niuē',None)
init_iso_lang('nld','nld',None,'nl','Dutch; Flemish','Individual','Living','Nederlands; Vlaams',None,synonim_iso639_2='dut')
init_iso_lang('nno','nno',None,'nn','Norwegian Nynorsk','Individual','Living','nynorsk','Nynorsk')
init_iso_lang('nob','nob',None,'nb','Norwegian Bokmål','Individual','Living','bokmål','Bokmål')
init_iso_lang('nog','nog',None,None,'Nogai','Individual','Living','Ногай тили',None)
init_iso_lang('non','non',None,None,'Old Norse','Individual','Historical','Dǫnsk tunga; Norrœnt mál',None)
init_iso_lang('nor','nor',None,'no','Norwegian','Macrolanguage','Living','norsk',None)
init_iso_lang('nqo','nqo',None,None,'N\'Ko','Individual','Living',None,None)
init_iso_lang('nso','nso',None,None,'Pedi; Sepedi; Northern Sotho','Individual','Living','Sesotho sa Leboa',None)
init_iso_lang('nub',None,'nub',None,'Nubian languages','Collective',None,'لغات نوبية',None)
init_iso_lang('nwc','nwc',None,None,'Classical Newari; Old Newari; Classical Nepal Bhasa','Individual','Historical','पुलां भाय्; पुलाङु नेपाल भाय्',None)
init_iso_lang('nya','nya',None,'ny','Chichewa; Chewa; Nyanja','Individual','Living','Chichewa; Chinyanja',None)
init_iso_lang('nym','nym',None,None,'Nyamwezi','Individual','Living',None,None)
init_iso_lang('nyn','nyn',None,None,'Nyankole','Individual','Living',None,'Nkore')
init_iso_lang('nyo','nyo',None,None,'Nyoro','Individual','Living','Runyoro',None)
init_iso_lang('nzi','nzi',None,None,'Nzima','Individual','Living',None,'Nzema')
init_iso_lang('oci','oci',None,'oc','Occitan (post 1500)','Individual','Living','occitan; lenga d\'òc; provençal',None)
init_iso_lang('oji','oji',None,'oj','Ojibwa','Macrolanguage','Living',None,'Ojibwe')
init_iso_lang('ori','ori',None,'or','Oriya','Macrolanguage','Living','ଓଡ଼ିଆ','Odia')
init_iso_lang('orm','orm',None,'om','Oromo','Macrolanguage','Living','Afaan Oromoo',None)
init_iso_lang('osa','osa',None,None,'Osage','Individual','Living','Wazhazhe ie / ???????????? ????',None)
init_iso_lang('oss','oss',None,'os','Ossetian; Ossetic','Individual','Living','Ирон æвзаг',None)
init_iso_lang('ota','ota',None,None,'Ottoman Turkish (1500–1928)','Individual','Historical','لسان عثمانى / lisân-ı Osmânî',None)
init_iso_lang('oto',None,'oto',None,'Otomian languages','Collective',None,None,'Oto-Pamean languages')
init_iso_lang('paa',None,'paa',None,'Papuan languages','Collective',None,None,None)
init_iso_lang('pag','pag',None,None,'Pangasinan','Individual','Living','Salitan Pangasinan',None)
init_iso_lang('pal','pal',None,None,'Pahlavi','Individual','Ancient','Pārsīk; Pārsīg','Middle Persian')
init_iso_lang('pam','pam',None,None,'Pampanga; Kapampangan','Individual','Living','Amánung Kapampangan; Amánung Sísuan',None)
init_iso_lang('pan','pan',None,'pa','Panjabi; Punjabi','Individual','Living','ਪੰਜਾਬੀ / پنجابی',None)
init_iso_lang('pap','pap',None,None,'Papiamento','Individual','Living','Papiamentu',None)
init_iso_lang('pau','pau',None,None,'Palauan','Individual','Living','a tekoi er a Belau',None)
init_iso_lang('peo','peo',None,None,'Old Persian (ca. 600–400 B.C.)','Individual','Historical',None,None)
init_iso_lang('phi',None,'phi',None,'Philippine languages','Collective',None,None,None)
init_iso_lang('phn','phn',None,None,'Phoenician','Individual','Ancient','?????????? ????????????',None)
init_iso_lang('pli','pli',None,'pi','Pali','Individual','Ancient','Pāli',None)
init_iso_lang('pol','pol',None,'pl','Polish','Individual','Living','Język polski',None)
init_iso_lang('pon','pon',None,None,'Pohnpeian','Individual','Living',None,None)
init_iso_lang('por','por',None,'pt','Portuguese','Individual','Living','português',None)
init_iso_lang('pra',None,'pra',None,'Prakrit languages','Collective',None,None,None)
init_iso_lang('pro','pro',None,None,'Old Provençal (to 1500); Old Occitan (to 1500)','Individual','Historical',None,None)
init_iso_lang('pus','pus',None,'ps','Pushto; Pashto','Macrolanguage','Living','پښتو',None)
init_iso_lang('qaa-qtz','qaa-qtz',None,None,'Reserved for local use','Local',None,None,None)
init_iso_lang('que','que',None,'qu','Quechua','Macrolanguage','Living','Runa simi; kichwa simi; Nuna shimi',None)
init_iso_lang('raj','raj',None,None,'Rajasthani','Macrolanguage','Living','राजस्थानी',None)
init_iso_lang('rap','rap',None,None,'Rapanui','Individual','Living','Vananga rapa nui',None)
init_iso_lang('rar','rar',None,None,'Rarotongan; Cook Islands Maori','Individual','Living','Māori Kūki \'Āirani',None)
init_iso_lang('roa',None,'roa',None,'Romance languages','Collective',None,None,None)
init_iso_lang('roh','roh',None,'rm','Romansh','Individual','Living','Rumantsch; Rumàntsch; Romauntsch; Romontsch',None)
init_iso_lang('rom','rom',None,None,'Romany','Macrolanguage','Living','romani čhib','Romani')
init_iso_lang('ron','ron',None,'ro','Romanian; Moldavian; Moldovan','Individual','Living','limba română',None,synonim_iso639_2='rum')
init_iso_lang('run','run',None,'rn','Rundi','Individual','Living','Ikirundi','Kirundi')
init_iso_lang('rup','rup',None,None,'Aromanian; Arumanian; Macedo-Romanian','Individual','Living','armãneashce; armãneashti; rrãmãneshti',None)
init_iso_lang('rus','rus',None,'ru','Russian','Individual','Living','русский язык',None)
init_iso_lang('sad','sad',None,None,'Sandawe','Individual','Living','Sandaweeki',None)
init_iso_lang('sag','sag',None,'sg','Sango','Individual','Living','yângâ tî sängö',None)
init_iso_lang('sah','sah',None,None,'Yakut','Individual','Living','Сахалыы',None)
init_iso_lang('sai',None,'sai',None,'South American Indian languages','Collective',None,None,None)
init_iso_lang('sal',None,'sal',None,'Salishan languages','Collective',None,None,None)
init_iso_lang('sam','sam',None,None,'Samaritan Aramaic','Individual','Extinct','ארמית',None)
init_iso_lang('san','san',None,'sa','Sanskrit','Individual','Ancient','संस्कृतम्',None)
init_iso_lang('sas','sas',None,None,'Sasak','Individual','Living',None,None)
init_iso_lang('sat','sat',None,None,'Santali','Individual','Living','ᱥᱟᱱᱛᱟᱲᱤ',None)
init_iso_lang('scn','scn',None,None,'Sicilian','Individual','Living','Sicilianu',None)
init_iso_lang('sco','sco',None,None,'Scots','Individual','Living','Braid Scots; Lallans',None)
init_iso_lang('sel','sel',None,None,'Selkup','Individual','Living',None,None)
init_iso_lang('sem',None,'sem',None,'Semitic languages','Collective',None,None,None)
init_iso_lang('sga','sga',None,None,'Old Irish (to 900)','Individual','Historical','Goídelc',None)
init_iso_lang('sgn',None,'sgn',None,'Sign languages','Collective',None,None,None)
init_iso_lang('shn','shn',None,None,'Shan','Individual','Living','ၵႂၢမ်းတႆးယႂ်',None)
init_iso_lang('sid','sid',None,None,'Sidamo','Individual','Living','Sidaamu Afoo',None)
init_iso_lang('sin','sin',None,'si','Sinhala; Sinhalese','Individual','Living','සිංහල',None)
init_iso_lang('sio',None,'sio',None,'Siouan languages','Collective',None,None,None)
init_iso_lang('sit',None,'sit',None,'Sino-Tibetan languages','Collective',None,None,None)
init_iso_lang('sla',None,'sla',None,'Slavic languages','Collective',None,None,None)
init_iso_lang('slk','slk',None,'sk','Slovak','Individual','Living','slovenčina; slovenský jazyk',None,synonim_iso639_2='slo')
init_iso_lang('slv','slv',None,'sl','Slovenian','Individual','Living','slovenski jezik; slovenščina','Slovene')
init_iso_lang('sma','sma',None,None,'Southern Sami','Individual','Living','Åarjelsaemien gïele',None)
init_iso_lang('sme','sme',None,'se','Northern Sami','Individual','Living','davvisámegiella',None)
init_iso_lang('smi',None,'smi',None,'Sami languages','Collective',None,None,None)
init_iso_lang('smj','smj',None,None,'Lule Sami','Individual','Living','julevsámegiella',None)
init_iso_lang('smn','smn',None,None,'Inari Sami','Individual','Living','anarâškielâ',None)
init_iso_lang('smo','smo',None,'sm','Samoan','Individual','Living','Gagana faʻa Sāmoa',None)
init_iso_lang('sms','sms',None,None,'Skolt Sami','Individual','Living','sääʹmǩiõll',None)
init_iso_lang('sna','sna',None,'sn','Shona','Individual','Living','chiShona',None)
init_iso_lang('snd','snd',None,'sd','Sindhi','Individual','Living','سنڌي / सिन्धी / ਸਿੰਧੀ',None)
init_iso_lang('snk','snk',None,None,'Soninke','Individual','Living','Sooninkanxanne',None)
init_iso_lang('sog','sog',None,None,'Sogdian','Individual','Ancient',None,None)
init_iso_lang('som','som',None,'so','Somali','Individual','Living','af Soomaali',None)
init_iso_lang('son',None,'son',None,'Songhai languages','Collective',None,None,'Songhay languages')
init_iso_lang('sot','sot',None,'st','Southern Sotho','Individual','Living','Sesotho [southern]',None)
init_iso_lang('spa','spa',None,'es','Spanish; Castilian','Individual','Living','español; castellano',None)
init_iso_lang('sqi','sqi',None,'sq','Albanian','Macrolanguage','Living','Shqip',None,synonim_iso639_2='alb')
init_iso_lang('srd','srd',None,'sc','Sardinian','Macrolanguage','Living','sardu; limba sarda; lingua sarda',None)
init_iso_lang('srn','srn',None,None,'Sranan Tongo','Individual','Living',None,None)
init_iso_lang('srp','srp',None,'sr','Serbian','Individual','Living','српски / srpski',None)
init_iso_lang('srr','srr',None,None,'Serer','Individual','Living','Seereer',None)
init_iso_lang('ssa',None,'ssa',None,'Nilo-Saharan languages','Collective',None,None,None)
init_iso_lang('ssw','ssw',None,'ss','Swati','Individual','Living','siSwati','Swazi')
init_iso_lang('suk','suk',None,None,'Sukuma','Individual','Living','Kɪsukuma',None)
init_iso_lang('sun','sun',None,'su','Sundanese','Individual','Living','ᮘᮞ ᮞᮥᮔ᮪ᮓ / Basa Sunda',None)
init_iso_lang('sus','sus',None,None,'Susu','Individual','Living','Sosoxui',None)
init_iso_lang('sux','sux',None,None,'Sumerian','Individual','Ancient','????',None)
init_iso_lang('swa','swa',None,'sw','Swahili','Macrolanguage','Living','Kiswahili',None)
init_iso_lang('swe','swe',None,'sv','Swedish','Individual','Living','svenska',None)
init_iso_lang('syc','syc',None,None,'Classical Syriac','Individual','Historical',None,None)
init_iso_lang('syr','syr',None,None,'Syriac','Macrolanguage','Living','ܠܫܢܐ ܣܘܪܝܝܐ',None)
init_iso_lang('tah','tah',None,'ty','Tahitian','Individual','Living','Reo Tahiti; Reo Mā\'ohi',None)
init_iso_lang('tai',None,'tai',None,'Tai languages','Collective',None,'ภาษาไท; ภาษาไต',None)
init_iso_lang('tam','tam',None,'ta','Tamil','Individual','Living','தமிழ்',None)
init_iso_lang('tat','tat',None,'tt','Tatar','Individual','Living','татар теле / tatar tele / تاتار',None)
init_iso_lang('tel','tel',None,'te','Telugu','Individual','Living','తెలుగు',None)
init_iso_lang('tem','tem',None,None,'Timne','Individual','Living','KʌThemnɛ','Temne')
init_iso_lang('ter','ter',None,None,'Tereno','Individual','Living','Terêna','Terena')
init_iso_lang('tet','tet',None,None,'Tetum','Individual','Living','Lia-Tetun',None)
init_iso_lang('tgk','tgk',None,'tg','Tajik','Individual','Living','тоҷикӣ / tojikī',None)
init_iso_lang('tgl','tgl',None,'tl','Tagalog','Individual','Living','Wikang Tagalog',None)
init_iso_lang('tha','tha',None,'th','Thai','Individual','Living','ภาษาไทย',None)
init_iso_lang('tig','tig',None,None,'Tigre','Individual','Living','ትግረ; ትግሬ; ኻሳ; ትግራይት',None)
init_iso_lang('tir','tir',None,'ti','Tigrinya','Individual','Living','ትግርኛ',None)
init_iso_lang('tiv','tiv',None,None,'Tiv','Individual','Living',None,None)
init_iso_lang('tkl','tkl',None,None,'Tokelau','Individual','Living',None,'Tokelauan')
init_iso_lang('tlh','tlh',None,None,'Klingon; tlhIngan-Hol','Individual','Constructed',None,None)
init_iso_lang('tli','tli',None,None,'Tlingit','Individual','Living','Lingít',None)
init_iso_lang('tmh','tmh',None,None,'Tamashek','Macrolanguage','Living',None,'Tamasheq')
init_iso_lang('tog','tog',None,None,'Tonga (Nyasa)','Individual','Living','chiTonga',None)
init_iso_lang('ton','ton',None,'to','Tonga (Tonga Islands)','Individual','Living','lea faka-Tonga','Tongan')
init_iso_lang('tpi','tpi',None,None,'Tok Pisin','Individual','Living',None,None)
init_iso_lang('tsi','tsi',None,None,'Tsimshian','Individual','Living',None,None)
init_iso_lang('tsn','tsn',None,'tn','Tswana','Individual','Living','Setswana',None)
init_iso_lang('tso','tso',None,'ts','Tsonga','Individual','Living','Xitsonga',None)
init_iso_lang('tuk','tuk',None,'tk','Turkmen','Individual','Living','Türkmençe / Түркменче / تورکمن تیلی ,تورکمنچه; türkmen dili / түркмен дили',None)
init_iso_lang('tum','tum',None,None,'Tumbuka','Individual','Living','chiTumbuka',None)
init_iso_lang('tup',None,'tup',None,'Tupi languages','Collective',None,None,'Tupian languages')
init_iso_lang('tur','tur',None,'tr','Turkish','Individual','Living','Türkçe',None)
init_iso_lang('tut',None,'tut',None,'Altaic languages','Collective',None,None,None)
init_iso_lang('tvl','tvl',None,None,'Tuvalua','Individual','Living','Te Ggana Tuuvalu; Te Gagana Tuuvalu','Tuvaluan')
init_iso_lang('twi','twi',None,'tw','Twi','Individual','Living',None,None)
init_iso_lang('tyv','tyv',None,None,'Tuvinian','Individual','Living','тыва дыл','Tuvan')
init_iso_lang('udm','udm',None,None,'Udmurt','Individual','Living','удмурт кыл',None)
init_iso_lang('uga','uga',None,None,'Ugaritic','Individual','Ancient',None,None)
init_iso_lang('uig','uig',None,'ug','Uighur; Uyghur','Individual','Living','ئۇيغۇرچە ; ئۇيغۇر تىلى',None)
init_iso_lang('ukr','ukr',None,'uk','Ukrainian','Individual','Living','українська мова',None)
init_iso_lang('umb','umb',None,None,'Umbundu','Individual','Living','Úmbúndú',None)
init_iso_lang('und','und',None,None,'Undetermined','Special',None,None,None)
init_iso_lang('urd','urd',None,'ur','Urdu','Individual','Living','اُردُو',None)
init_iso_lang('uzb','uzb',None,'uz','Uzbek','Macrolanguage','Living','Oʻzbekcha / ўзбекча / ئوزبېچه; oʻzbek tili / ўзбек тили / ئوبېک تیلی',None)
init_iso_lang('vai','vai',None,None,'Vai','Individual','Living','ꕙꔤ',None)
init_iso_lang('ven','ven',None,'ve','Venda','Individual','Living','Tshivenḓa',None)
init_iso_lang('vie','vie',None,'vi','Vietnamese','Individual','Living','Tiếng Việt',None)
init_iso_lang('vol','vol',None,'vo','Volapük','Individual','Constructed',None,None)
init_iso_lang('vot','vot',None,None,'Votic','Individual','Living','vađđa ceeli',None)
init_iso_lang('wak',None,'wak',None,'Wakashan languages','Collective',None,None,None)
init_iso_lang('wal','wal',None,None,'Wolaitta; Wolaytta','Individual','Living',None,None)
init_iso_lang('war','war',None,None,'Waray','Individual','Living','Winaray; Samareño; Lineyte-Samarnon; Binisayâ nga Winaray; Binisayâ nga Samar-Leyte; “Binisayâ nga Waray”',None)
init_iso_lang('was','was',None,None,'Washo','Individual','Living','wá:šiw ʔítlu',None)
init_iso_lang('wen',None,'wen',None,'Sorbian languages','Collective',None,'Serbsce / Serbski',None)
init_iso_lang('wln','wln',None,'wa','Walloon','Individual','Living','Walon',None)
init_iso_lang('wol','wol',None,'wo','Wolof','Individual','Living',None,None)
init_iso_lang('xal','xal',None,None,'Kalmyk; Oirat','Individual','Living','Хальмг келн / Xaľmg keln',None)
init_iso_lang('xho','xho',None,'xh','Xhosa','Individual','Living','isiXhosa',None)
init_iso_lang('yao','yao',None,None,'Yao','Individual','Living',None,None)
init_iso_lang('yap','yap',None,None,'Yapese','Individual','Living',None,None)
init_iso_lang('yid','yid',None,'yi','Yiddish','Macrolanguage','Living','ייִדיש, יידיש; אידיש',None)
init_iso_lang('yor','yor',None,'yo','Yoruba','Individual','Living','èdè Yorùbá',None)
init_iso_lang('ypk',None,'ypk',None,'Yupik languages','Collective',None,None,None)
init_iso_lang('zap','zap',None,None,'Zapotec','Macrolanguage','Living','Diidxazá',None)
init_iso_lang('zbl','zbl',None,None,'Blissymbols; Blissymbolics; Bliss','Individual','Constructed',None,None)
init_iso_lang('zen','zen',None,None,'Zenaga','Individual','Living','Tuḍḍungiyya',None)
init_iso_lang('zgh','zgh',None,None,'Standard Moroccan Tamazight','Individual','Living','ⵜⴰⵎⴰⵣⵉⵖⵜ ⵜⴰⵏⴰⵡⴰⵢⵜ','Standard Moroccan Berber')
init_iso_lang('zha','zha',None,'za','Zhuang; Chuang','Macrolanguage','Living','Vahcuengh / 話僮',None)
init_iso_lang('zho','zho',None,'zh','Chinese','Macrolanguage','Living','中文; 汉语; 漢語',None,synonim_iso639_2='chi')
init_iso_lang('znd',None,'znd',None,'Zande languages','Collective',None,None,None)
init_iso_lang('zul','zul',None,'zu','Zulu','Individual','Living','isiZulu',None)
init_iso_lang('zun','zun',None,None,'Zuni','Individual','Living','Shiwi\'ma',None)
init_iso_lang('zxx','zxx',None,None,'No linguistic content; Not applicable','Special',None,None,None)
init_iso_lang('zza','zza',None,None,'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki','Macrolanguage','Living',None,None)

def isolang(v):
    if type(v) is str:
        try:
            return iso_lang_map[v.lower()]
        except KeyError:
            raise ValueError('Unrecognized language code %r' % (v,))
    elif isinstance(v, IsoLang):
        return v  # Unique!
    else:
        raise TypeError(v)

# vim: ft=python ts=8 sw=4 sts=4 ai et fdm=marker
